### ISSUE TITLE
Bug in mddc

### ISSUE THREAD

**Issue by ghost** [nicospavlidis/opc#1]
Hello,

When I use mddc for clustering the attached 
[dataseterror.txt](https://github.com/nicospavlidis/opc/files/4697772/dataseterror.txt)
file, it gives the error below. Hope it can help to improve the quality of the toolbox. 

code: 
[labels, t1] = mddc(data,4) ;

Error:
Clusters: 1 Error using fminusub (line 16)
Objective function is undefined at initial point. Fminunc cannot continue.

Error in fminunc (line 462)
   [x,FVAL,GRAD,HESSIAN,EXITFLAG,OUTPUT] = fminusub(funfcn,x, ...

Error in mdpp>BFGS (line 216)
[x, fval, exitflag] = fminunc(objfungrad, x, options);

Error in mdpp>mdpp_internal (line 172)
	[x,fx,it] = BFGS(x, Data, pars, labels, colours);

Error in mdpp (line 102)
	[sol, exitflag] = mdpp_internal(Data, V(:,i), pars, labels, colours);

Error in mddc (line 180)
		[opthp, pass{j}, split_index(j)] = mdpp(X(list{j},:), pars, la, cl);

**Comment by nicospavlidis** [comment]
Thank you for identifying this bug in the code.

This has now been fixed
