### ISSUE TITLE
bug for mddc 2

### ISSUE THREAD

**Issue by ghost** [nicospavlidis/opc#2]
Hi!

Thank you for your powerful toolbox.

mddc function gives the following error when it is used for clustering the attached file. I hope it can help to improve the quality of the toolbox. 

[DatasetError2.txt](https://github.com/nicospavlidis/opc/files/4697865/DatasetError2.txt)

Error using vertcat
Dimensions of arrays being concatenated are not consistent.

Error in f_md (line 140)
				bmin = [bmin; xmin];

Error in f_df_md (line 19)
[f, bmin] = f_md(v,X,pars);

Error in mdpp>@(v)f_df_md(v,Data,pars) (line 205)
objfungrad = @(v)f_df_md(v,Data,pars);

Error in fminunc (line 303)
        [f,GRAD] = feval(funfcn{3},x,varargin{:});

Error in mdpp>BFGS (line 216)
[x, fval, exitflag] = fminunc(objfungrad, x, options);

Error in mdpp>mdpp_internal (line 172)
	[x,fx,it] = BFGS(x, Data, pars, labels, colours);

Error in mdpp (line 102)
	[sol, exitflag] = mdpp_internal(Data, V(:,i), pars, labels, colours);

Error in mddc (line 137)
[opthp, pass{1}, split_index(1)] = mdpp(X, pars, pars.labels, pars.colours);

Caused by:
    Failure in initial objective function evaluation. FMINUNC cannot continue.

**Comment by nicospavlidis** [comment]
Thank you for identifying this bug. It has now been corrected.
